name: eshop_multivendor
description: eShop Multivendor App

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^9.9.1 
  path_provider: ^2.0.10
  firebase_messaging: ^11.4.1
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  firebase_auth: ^3.3.19
  sms_autofill: ^2.2.0
  intl: ^0.17.0
  country_code_picker: ^2.0.2
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  file_picker: ^4.6.1
  shimmer: ^2.0.0
  geocoding: ^2.0.2
  razorpay_flutter: ^1.3.3
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^10.2.0
  in_app_review: ^2.0.4
  firebase_dynamic_links: ^4.3.11
  open_file: ^3.2.1
  provider: ^6.0.4
  share_plus: ^4.0.5
  video_player: ^2.4.2
  flutter_svg: ^1.1.5
  paytm: ^3.0.1
  youtube_player_flutter: ^8.1.0
  package_info: ^2.0.2
  url_launcher: ^6.1.6
  sqflite: ^2.1.0+1
  version: ^3.0.2
  flutter_downloader: ^1.8.4
  speech_to_text: ^5.5.0
  tuple: ^2.0.1
  cached_network_image: ^3.2.2
  lottie: ^1.4.3
  flutter_stripe: ^3.0.2
  flutter_widget_from_html: ^0.9.0+1
  flutter_html: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.5.0+4
  my_fatoorah: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/animation/
    - lib/Language/
    - assets/eShop.db

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf